---
- hosts: server
  gather_facts: false
  become: yes
  become_user: ubuntu
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
    # Create Kubernetes replica set
    - name: Create replicaset object
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: ReplicaSet
          metadata:
            name: xxxxxx
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: xxxxxx
            template:
              metadata:
                labels:
                  app: xxxxxx
              spec:
                containers:
                - name: xxxxxx
                  image: xxxxxx
                  ports:
                  - containerPort: 8080
                imagePullSecrets:
                - name: xxxxxx

    - name: Create a Service to access spring app
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: xxxxx
            namespace: default
          spec:
            type: NodePort
            ports:
            - port: 8080
              nodePort: 30003
              protocol: TCP
            selector:
              app: xxxxxx
